<?php

namespace Marando\Interp;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-29 at 12:49:07.
 */
class LagrangeTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\Interp\Lagrange::x
   */
  public function testX() {
    $data = [
        [29.43, .4913598528],
        [30.97, .5145891926],
        [27.69, .4646875083],
        [28.11, .4711658342],
        [31.58, .5236885653],
        [33.05, .5453707057],
    ];

    $tests = [
        30 => 0.5,
        0  => 0.0000512249,
        90 => 0.9999648100,
    ];

    $l = Lagrange::init($data);
    foreach ($tests as $x => $exy) {
      $l->x($x, $y);
      $this->assertEquals($exy, $y, $x, 1e-10);
    }
  }

}
